
export const itemsData = {
    "id": "aq1w34fr",
    "data": [
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        }
        , {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "SHREE KRISHNA EXPORTS | +91 8758734381 | Rahul Tejani | ",
            "shape": "Round",
            "carat": 1.04,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3360.0,
            "total_price": 3494.4,
            "table %": 61.0,
            "depth %": 59.4,
            "certificate #": "6452605117",
            "lab": "GIA",
            "report date": "2023-02-16T00:00:00",
            "key to symbols": "Crystal, Feather, Needle, Indented Natural, Natural",
            "cert comment": "",
            "member comment": "NO BGM,TABLE SMALL BLACK,SIDE SMALL BLACK",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.62,
            "length": 6.58,
            "height": 3.92,
            "city": null,
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Thin",
            "girdle max": "Medium",
            "girdle %": 3.5,
            "girdle condition": "Faceted",
            "PA": 40.8,
            "PD": 43.0,
            "CH": 13.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "E1",
            "videolink": null,
            "imagename1": "https://skrishna.co/DiamondDetail/DiamondDetail?stoneno=17-61",
            "cert url": "http://www.gia.edu/cs/Satellite?reportno=6452605117&childpagename=GIA%2FPage%2FReportCheck&pagename=GIA%2FDispatcher&c=Page&cid=1355954554547",
            "BIC": "",
            "BIS": "",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UNIQUE GEMS | 91 22 40178888 | DEVAL TEJANI | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3362.4,
            "total_price": 3396.024,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits - www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        },
        {
            "Stock No": "UniBlue HK Limited | +852 67058899 | Gopal Parekh | ",
            "shape": "Round",
            "carat": 1.01,
            "color": "D",
            "clarity": "SI1",
            "cut": "EX",
            "polish": "EX",
            "symmetry": "EX",
            "price_per_carat": 3366.4,
            "total_price": 3400.064,
            "table %": 58.0,
            "depth %": 61.4,
            "certificate #": "2447830060",
            "lab": "GIA",
            "report date": "2022-09-30T00:00:00",
            "key to symbols": "Feather, Twinning Wisp, Crystal, Natural",
            "cert comment": "",
            "member comment": "register on our website to get more benefits -  www.unique.diamonds",
            "black inclusion": null,
            "center inclusion": null,
            "open inclusion": null,
            "width": 6.47,
            "length": 6.43,
            "height": 3.96,
            "city": "Mumbai",
            "country": "India",
            "fluor": "S",
            "fluor color": "B",
            "culet condition": null,
            "culet size": "None",
            "girdle min": "Slightly Thick",
            "girdle max": "Slightly Thick",
            "girdle %": 4.0,
            "girdle condition": "Faceted",
            "PA": 41.2,
            "PD": 43.5,
            "CH": 14.0,
            "CA": 33.5,
            "availability": "G",
            "shade": "None",
            "milky": "None",
            "eyeclean": "Yes",
            "videolink": null,
            "imagename1": "https://client.unique.diamonds/dna/11271-68",
            "cert url": "",
            "BIC": "Medium",
            "BIS": "Medium",
            "WIC": "",
            "WIS": "",
            "OP": "",
            "OT": "",
            "OC": ""
        }
    ]
}